---
- name: Setup Ubuntu 24.04 for free5GC on Azure VM
  hosts: azure_vms
  become: yes
  tasks:
    - name: Import package installation tasks
      import_tasks: tasks/install_packages.yml

    - name: Import microk8s installation tasks
      import_tasks: tasks/install_microk8s.yml

    - name: Import Helm installation tasks
      import_tasks: tasks/install_helm.yml
