---
- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Install Helm
  command: /tmp/get_helm.sh
  register: helm_install
  changed_when: helm_install.rc == 0

- name: Verify Helm installation
  command: helm version
  register: helm_version
  changed_when: false
  failed_when: helm_version.rc != 0
