---
- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
    state: present

- name: Add current user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: Wait for MicroK8s to be ready
  command: microk8s status --wait-ready
  changed_when: false
  register: microk8s_status
  until: microk8s_status.rc == 0
  retries: 10
  delay: 10

- name: Enable MicroK8s addons
  command: microk8s enable {{ item }}
  changed_when: true
  with_items:
    - community
    - dns
    - storage
    - rbac
    - multus
  register: enable_addons
  until: enable_addons.rc == 0
  retries: 3
  delay: 10

- name: Create .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'
  become: no

- name: Create kubectl config file
  command: microk8s config > {{ ansible_env.HOME }}/.kube/config
  args:
    creates: "{{ ansible_env.HOME }}/.kube/config"
  become: no
  changed_when: true

- name: Set correct permissions for kubectl config file
  file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: no
