---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - gcc 
      - g++
      - cmake 
      - autoconf 
      - libtool 
      - pkg-config 
      - libmnl-dev 
      - libyaml-dev
    state: present
